import 'country.dart';

final countries = [
const Country(name: "Afghanistan", countryCode: "AF", dialCode: "+93", emoji: "🇦🇫", flagUri: "assets/svg/af.png"),
const Country(name: "Aland Islands", countryCode: "AX", dialCode: "+358", emoji: "🇦🇽", flagUri: "assets/svg/ax.png"),
const Country(name: "Albania", countryCode: "AL", dialCode: "+355", emoji: "🇦🇱", flagUri: "assets/svg/al.png"),
const Country(name: "Algeria", countryCode: "DZ", dialCode: "+213", emoji: "🇩🇿", flagUri: "assets/svg/dz.png"),
const Country(name: "AmericanSamoa", countryCode: "AS", dialCode: "+1684", emoji: "🇦🇸", flagUri: "assets/svg/as.png"),
const Country(name: "Andorra", countryCode: "AD", dialCode: "+376", emoji: "🇦🇩", flagUri: "assets/svg/ad.png"),
const Country(name: "Angola", countryCode: "AO", dialCode: "+244", emoji: "🇦🇴", flagUri: "assets/svg/ao.png"),
const Country(name: "Anguilla", countryCode: "AI", dialCode: "+1264", emoji: "🇦🇮", flagUri: "assets/svg/ai.png"),
const Country(name: "Antarctica", countryCode: "AQ", dialCode: "+672", emoji: "🇦🇶", flagUri: "assets/svg/aq.png"),
const Country(name: "Antigua and Barbuda", countryCode: "AG", dialCode: "+1268", emoji: "🇦🇬", flagUri: "assets/svg/ag.png"),
const Country(name: "Argentina", countryCode: "AR", dialCode: "+54", emoji: "🇦🇷", flagUri: "assets/svg/ar.png"),
const Country(name: "Armenia", countryCode: "AM", dialCode: "+374", emoji: "🇦🇲", flagUri: "assets/svg/am.png"),
const Country(name: "Aruba", countryCode: "AW", dialCode: "+297", emoji: "🇦🇼", flagUri: "assets/svg/aw.png"),
const Country(name: "Australia", countryCode: "AU", dialCode: "+61", emoji: "🇦🇺", flagUri: "assets/svg/au.png"),
const Country(name: "Austria", countryCode: "AT", dialCode: "+43", emoji: "🇦🇹", flagUri: "assets/svg/at.png"),
const Country(name: "Azerbaijan", countryCode: "AZ", dialCode: "+994", emoji: "🇦🇿", flagUri: "assets/svg/az.png"),
const Country(name: "Bahamas", countryCode: "BS", dialCode: "+1242", emoji: "🇧🇸", flagUri: "assets/svg/bs.png"),
const Country(name: "Bahrain", countryCode: "BH", dialCode: "+973", emoji: "🇧🇭", flagUri: "assets/svg/bh.png"),
const Country(name: "Bangladesh", countryCode: "BD", dialCode: "+880", emoji: "🇧🇩", flagUri: "assets/svg/bd.png"),
const Country(name: "Barbados", countryCode: "BB", dialCode: "+1246", emoji: "🇧🇧", flagUri: "assets/svg/bb.png"),
const Country(name: "Belarus", countryCode: "BY", dialCode: "+375", emoji: "🇧🇾", flagUri: "assets/svg/by.png"),
const Country(name: "Belgium", countryCode: "BE", dialCode: "+32", emoji: "🇧🇪", flagUri: "assets/svg/be.png"),
const Country(name: "Belize", countryCode: "BZ", dialCode: "+501", emoji: "🇧🇿", flagUri: "assets/svg/bz.png"),
const Country(name: "Benin", countryCode: "BJ", dialCode: "+229", emoji: "🇧🇯", flagUri: "assets/svg/bj.png"),
const Country(name: "Bermuda", countryCode: "BM", dialCode: "+1441", emoji: "🇧🇲", flagUri: "assets/svg/bm.png"),
const Country(name: "Bhutan", countryCode: "BT", dialCode: "+975", emoji: "🇧🇹", flagUri: "assets/svg/bt.png"),
const Country(name: "Bolivia, Plurinational State of", countryCode: "BO", dialCode: "+591", emoji: "🇧🇴", flagUri: "assets/svg/bo.png"),
const Country(name: "Bosnia and Herzegovina", countryCode: "BA", dialCode: "+387", emoji: "🇧🇦", flagUri: "assets/svg/ba.png"),
const Country(name: "Botswana", countryCode: "BW", dialCode: "+267", emoji: "🇧🇼", flagUri: "assets/svg/bw.png"),
const Country(name: "Brazil", countryCode: "BR", dialCode: "+55", emoji: "🇧🇷", flagUri: "assets/svg/br.png"),
const Country(name: "British Indian Ocean Territory", countryCode: "IO", dialCode: "+246", emoji: "🇮🇴", flagUri: "assets/svg/io.png"),
const Country(name: "Brunei Darussalam", countryCode: "BN", dialCode: "+673", emoji: "🇧🇳", flagUri: "assets/svg/bn.png"),
const Country(name: "Bulgaria", countryCode: "BG", dialCode: "+359", emoji: "🇧🇬", flagUri: "assets/svg/bg.png"),
const Country(name: "Burkina Faso", countryCode: "BF", dialCode: "+226", emoji: "🇧🇫", flagUri: "assets/svg/bf.png"),
const Country(name: "Burundi", countryCode: "BI", dialCode: "+257", emoji: "🇧🇮", flagUri: "assets/svg/bi.png"),
const Country(name: "Cambodia", countryCode: "KH", dialCode: "+855", emoji: "🇰🇭", flagUri: "assets/svg/kh.png"),
const Country(name: "Cameroon", countryCode: "CM", dialCode: "+237", emoji: "🇨🇲", flagUri: "assets/svg/cm.png"),
const Country(name: "Canada", countryCode: "CA", dialCode: "+1", emoji: "🇨🇦", flagUri: "assets/svg/ca.png"),
const Country(name: "Cape Verde", countryCode: "CV", dialCode: "+238", emoji: "🇨🇻", flagUri: "assets/svg/cv.png"),
const Country(name: "Cayman Islands", countryCode: "KY", dialCode: "+ 345", emoji: "🇰🇾", flagUri: "assets/svg/ky.png"),
const Country(name: "Central African Republic", countryCode: "CF", dialCode: "+236", emoji: "🇨🇫", flagUri: "assets/svg/cf.png"),
const Country(name: "Chad", countryCode: "TD", dialCode: "+235", emoji: "🇹🇩", flagUri: "assets/svg/td.png"),
const Country(name: "Chile", countryCode: "CL", dialCode: "+56", emoji: "🇨🇱", flagUri: "assets/svg/cl.png"),
const Country(name: "China", countryCode: "CN", dialCode: "+86", emoji: "🇨🇳", flagUri: "assets/svg/cn.png"),
const Country(name: "Christmas Island", countryCode: "CX", dialCode: "+61", emoji: "🇨🇽", flagUri: "assets/svg/cx.png"),
const Country(name: "Cocos (Keeling) Islands", countryCode: "CC", dialCode: "+61", emoji: "🇨🇨", flagUri: "assets/svg/cc.png"),
const Country(name: "Colombia", countryCode: "CO", dialCode: "+57", emoji: "🇨🇴", flagUri: "assets/svg/co.png"),
const Country(name: "Comoros", countryCode: "KM", dialCode: "+269", emoji: "🇰🇲", flagUri: "assets/svg/km.png"),
const Country(name: "Congo", countryCode: "CG", dialCode: "+242", emoji: "🇨🇬", flagUri: "assets/svg/cg.png"),
const Country(name: "Congo, The Democratic Republic of the Congo", countryCode: "CD", dialCode: "+243", emoji: "🇨🇩", flagUri: "assets/svg/cd.png"),
const Country(name: "Cook Islands", countryCode: "CK", dialCode: "+682", emoji: "🇨🇰", flagUri: "assets/svg/ck.png"),
const Country(name: "Costa Rica", countryCode: "CR", dialCode: "+506", emoji: "🇨🇷", flagUri: "assets/svg/cr.png"),
const Country(name: "Cote d'Ivoire", countryCode: "CI", dialCode: "+225", emoji: "🇨🇮", flagUri: "assets/svg/ci.png"),
const Country(name: "Croatia", countryCode: "HR", dialCode: "+385", emoji: "🇭🇷", flagUri: "assets/svg/hr.png"),
const Country(name: "Cuba", countryCode: "CU", dialCode: "+53", emoji: "🇨🇺", flagUri: "assets/svg/cu.png"),
const Country(name: "Cyprus", countryCode: "CY", dialCode: "+357", emoji: "🇨🇾", flagUri: "assets/svg/cy.png"),
const Country(name: "Czech Republic", countryCode: "CZ", dialCode: "+420", emoji: "🇨🇿", flagUri: "assets/svg/cz.png"),
const Country(name: "Denmark", countryCode: "DK", dialCode: "+45", emoji: "🇩🇰", flagUri: "assets/svg/dk.png"),
const Country(name: "Djibouti", countryCode: "DJ", dialCode: "+253", emoji: "🇩🇯", flagUri: "assets/svg/dj.png"),
const Country(name: "Dominica", countryCode: "DM", dialCode: "+1767", emoji: "🇩🇲", flagUri: "assets/svg/dm.png"),
const Country(name: "Dominican Republic", countryCode: "DO", dialCode: "+1849", emoji: "🇩🇴", flagUri: "assets/svg/do.png"),
const Country(name: "Ecuador", countryCode: "EC", dialCode: "+593", emoji: "🇪🇨", flagUri: "assets/svg/ec.png"),
const Country(name: "Egypt", countryCode: "EG", dialCode: "+20", emoji: "🇪🇬", flagUri: "assets/svg/eg.png"),
const Country(name: "El Salvador", countryCode: "SV", dialCode: "+503", emoji: "🇸🇻", flagUri: "assets/svg/sv.png"),
const Country(name: "Equatorial Guinea", countryCode: "GQ", dialCode: "+240", emoji: "🇬🇶", flagUri: "assets/svg/gq.png"),
const Country(name: "Eritrea", countryCode: "ER", dialCode: "+291", emoji: "🇪🇷", flagUri: "assets/svg/er.png"),
const Country(name: "Estonia", countryCode: "EE", dialCode: "+372", emoji: "🇪🇪", flagUri: "assets/svg/ee.png"),
const Country(name: "Ethiopia", countryCode: "ET", dialCode: "+251", emoji: "🇪🇹", flagUri: "assets/svg/et.png"),
const Country(name: "Falkland Islands (Malvinas)", countryCode: "FK", dialCode: "+500", emoji: "🇫🇰", flagUri: "assets/svg/fk.png"),
const Country(name: "Faroe Islands", countryCode: "FO", dialCode: "+298", emoji: "🇫🇴", flagUri: "assets/svg/fo.png"),
const Country(name: "Fiji", countryCode: "FJ", dialCode: "+679", emoji: "🇫🇯", flagUri: "assets/svg/fj.png"),
const Country(name: "Finland", countryCode: "FI", dialCode: "+358", emoji: "🇫🇮", flagUri: "assets/svg/fi.png"),
const Country(name: "France", countryCode: "FR", dialCode: "+33", emoji: "🇫🇷", flagUri: "assets/svg/fr.png"),
const Country(name: "French Guiana", countryCode: "GF", dialCode: "+594", emoji: "🇬🇫", flagUri: "assets/svg/gf.png"),
const Country(name: "French Polynesia", countryCode: "PF", dialCode: "+689", emoji: "🇵🇫", flagUri: "assets/svg/pf.png"),
const Country(name: "Gabon", countryCode: "GA", dialCode: "+241", emoji: "🇬🇦", flagUri: "assets/svg/ga.png"),
const Country(name: "Gambia", countryCode: "GM", dialCode: "+220", emoji: "🇬🇲", flagUri: "assets/svg/gm.png"),
const Country(name: "Georgia", countryCode: "GE", dialCode: "+995", emoji: "🇬🇪", flagUri: "assets/svg/ge.png"),
const Country(name: "Germany", countryCode: "DE", dialCode: "+49", emoji: "🇩🇪", flagUri: "assets/svg/de.png"),
const Country(name: "Ghana", countryCode: "GH", dialCode: "+233", emoji: "🇬🇭", flagUri: "assets/svg/gh.png"),
const Country(name: "Gibraltar", countryCode: "GI", dialCode: "+350", emoji: "🇬🇮", flagUri: "assets/svg/gi.png"),
const Country(name: "Greece", countryCode: "GR", dialCode: "+30", emoji: "🇬🇷", flagUri: "assets/svg/gr.png"),
const Country(name: "Greenland", countryCode: "GL", dialCode: "+299", emoji: "🇬🇱", flagUri: "assets/svg/gl.png"),
const Country(name: "Grenada", countryCode: "GD", dialCode: "+1473", emoji: "🇬🇩", flagUri: "assets/svg/gd.png"),
const Country(name: "Guadeloupe", countryCode: "GP", dialCode: "+590", emoji: "🇬🇵", flagUri: "assets/svg/gp.png"),
const Country(name: "Guam", countryCode: "GU", dialCode: "+1671", emoji: "🇬🇺", flagUri: "assets/svg/gu.png"),
const Country(name: "Guatemala", countryCode: "GT", dialCode: "+502", emoji: "🇬🇹", flagUri: "assets/svg/gt.png"),
const Country(name: "Guernsey", countryCode: "GG", dialCode: "+44", emoji: "🇬🇬", flagUri: "assets/svg/gg.png"),
const Country(name: "Guinea", countryCode: "GN", dialCode: "+224", emoji: "🇬🇳", flagUri: "assets/svg/gn.png"),
const Country(name: "Guinea-Bissau", countryCode: "GW", dialCode: "+245", emoji: "🇬🇼", flagUri: "assets/svg/gw.png"),
const Country(name: "Guyana", countryCode: "GY", dialCode: "+595", emoji: "🇬🇾", flagUri: "assets/svg/gy.png"),
const Country(name: "Haiti", countryCode: "HT", dialCode: "+509", emoji: "🇭🇹", flagUri: "assets/svg/ht.png"),
const Country(name: "Holy See (Vatican City State)", countryCode: "VA", dialCode: "+379", emoji: "🇻🇦", flagUri: "assets/svg/va.png"),
const Country(name: "Honduras", countryCode: "HN", dialCode: "+504", emoji: "🇭🇳", flagUri: "assets/svg/hn.png"),
const Country(name: "Hong Kong", countryCode: "HK", dialCode: "+852", emoji: "🇭🇰", flagUri: "assets/svg/hk.png"),
const Country(name: "Hungary", countryCode: "HU", dialCode: "+36", emoji: "🇭🇺", flagUri: "assets/svg/hu.png"),
const Country(name: "Iceland", countryCode: "IS", dialCode: "+354", emoji: "🇮🇸", flagUri: "assets/svg/is.png"),
const Country(name: "India", countryCode: "IN", dialCode: "+91", emoji: "🇮🇳", flagUri: "assets/svg/in.png"),
const Country(name: "Indonesia", countryCode: "ID", dialCode: "+62", emoji: "🇮🇩", flagUri: "assets/svg/id.png"),
const Country(name: "Iran, Islamic Republic of Persian Gulf", countryCode: "IR", dialCode: "+98", emoji: "🇮🇷", flagUri: "assets/svg/ir.png"),
const Country(name: "Iraq", countryCode: "IQ", dialCode: "+964", emoji: "🇮🇶", flagUri: "assets/svg/iq.png"),
const Country(name: "Ireland", countryCode: "IE", dialCode: "+353", emoji: "🇮🇪", flagUri: "assets/svg/ie.png"),
const Country(name: "Isle of Man", countryCode: "IM", dialCode: "+44", emoji: "🇮🇲", flagUri: "assets/svg/im.png"),
const Country(name: "Israel", countryCode: "IL", dialCode: "+972", emoji: "🇮🇱", flagUri: "assets/svg/il.png"),
const Country(name: "Italy", countryCode: "IT", dialCode: "+39", emoji: "🇮🇹", flagUri: "assets/svg/it.png"),
const Country(name: "Jamaica", countryCode: "JM", dialCode: "+1876", emoji: "🇯🇲", flagUri: "assets/svg/jm.png"),
const Country(name: "Japan", countryCode: "JP", dialCode: "+81", emoji: "🇯🇵", flagUri: "assets/svg/jp.png"),
const Country(name: "Jersey", countryCode: "JE", dialCode: "+44", emoji: "🇯🇪", flagUri: "assets/svg/je.png"),
const Country(name: "Jordan", countryCode: "JO", dialCode: "+962", emoji: "🇯🇴", flagUri: "assets/svg/jo.png"),
const Country(name: "Kazakhstan", countryCode: "KZ", dialCode: "+77", emoji: "🇰🇿", flagUri: "assets/svg/kz.png"),
const Country(name: "Kenya", countryCode: "KE", dialCode: "+254", emoji: "🇰🇪", flagUri: "assets/svg/ke.png"),
const Country(name: "Kiribati", countryCode: "KI", dialCode: "+686", emoji: "🇰🇮", flagUri: "assets/svg/ki.png"),
const Country(name: "Korea, Democratic People's Republic of Korea", countryCode: "KP", dialCode: "+850", emoji: "🇰🇵", flagUri: "assets/svg/kp.png"),
const Country(name: "Korea, Republic of South Korea", countryCode: "KR", dialCode: "+82", emoji: "🇰🇷", flagUri: "assets/svg/kr.png"),
const Country(name: "Kuwait", countryCode: "KW", dialCode: "+965", emoji: "🇰🇼", flagUri: "assets/svg/kw.png"),
const Country(name: "Kyrgyzstan", countryCode: "KG", dialCode: "+996", emoji: "🇰🇬", flagUri: "assets/svg/kg.png"),
const Country(name: "Laos", countryCode: "LA", dialCode: "+856", emoji: "🇱🇦", flagUri: "assets/svg/la.png"),
const Country(name: "Latvia", countryCode: "LV", dialCode: "+371", emoji: "🇱🇻", flagUri: "assets/svg/lv.png"),
const Country(name: "Lebanon", countryCode: "LB", dialCode: "+961", emoji: "🇱🇧", flagUri: "assets/svg/lb.png"),
const Country(name: "Lesotho", countryCode: "LS", dialCode: "+266", emoji: "🇱🇸", flagUri: "assets/svg/ls.png"),
const Country(name: "Liberia", countryCode: "LR", dialCode: "+231", emoji: "🇱🇷", flagUri: "assets/svg/lr.png"),
const Country(name: "Libyan Arab Jamahiriya", countryCode: "LY", dialCode: "+218", emoji: "🇱🇾", flagUri: "assets/svg/ly.png"),
const Country(name: "Liechtenstein", countryCode: "LI", dialCode: "+423", emoji: "🇱🇮", flagUri: "assets/svg/li.png"),
const Country(name: "Lithuania", countryCode: "LT", dialCode: "+370", emoji: "🇱🇹", flagUri: "assets/svg/lt.png"),
const Country(name: "Luxembourg", countryCode: "LU", dialCode: "+352", emoji: "🇱🇺", flagUri: "assets/svg/lu.png"),
const Country(name: "Macao", countryCode: "MO", dialCode: "+853", emoji: "🇲🇴", flagUri: "assets/svg/mo.png"),
const Country(name: "Macedonia", countryCode: "MK", dialCode: "+389", emoji: "🇲🇰", flagUri: "assets/svg/mk.png"),
const Country(name: "Madagascar", countryCode: "MG", dialCode: "+261", emoji: "🇲🇬", flagUri: "assets/svg/mg.png"),
const Country(name: "Malawi", countryCode: "MW", dialCode: "+265", emoji: "🇲🇼", flagUri: "assets/svg/mw.png"),
const Country(name: "Malaysia", countryCode: "MY", dialCode: "+60", emoji: "🇲🇾", flagUri: "assets/svg/my.png"),
const Country(name: "Maldives", countryCode: "MV", dialCode: "+960", emoji: "🇲🇻", flagUri: "assets/svg/mv.png"),
const Country(name: "Mali", countryCode: "ML", dialCode: "+223", emoji: "🇲🇱", flagUri: "assets/svg/ml.png"),
const Country(name: "Malta", countryCode: "MT", dialCode: "+356", emoji: "🇲🇹", flagUri: "assets/svg/mt.png"),
const Country(name: "Marshall Islands", countryCode: "MH", dialCode: "+692", emoji: "🇲🇭", flagUri: "assets/svg/mh.png"),
const Country(name: "Martinique", countryCode: "MQ", dialCode: "+596", emoji: "🇲🇶", flagUri: "assets/svg/mq.png"),
const Country(name: "Mauritania", countryCode: "MR", dialCode: "+222", emoji: "🇲🇷", flagUri: "assets/svg/mr.png"),
const Country(name: "Mauritius", countryCode: "MU", dialCode: "+230", emoji: "🇲🇺", flagUri: "assets/svg/mu.png"),
const Country(name: "Mayotte", countryCode: "YT", dialCode: "+262", emoji: "🇾🇹", flagUri: "assets/svg/yt.png"),
const Country(name: "Mexico", countryCode: "MX", dialCode: "+52", emoji: "🇲🇽", flagUri: "assets/svg/mx.png"),
const Country(name: "Micronesia, Federated States of Micronesia", countryCode: "FM", dialCode: "+691", emoji: "🇫🇲", flagUri: "assets/svg/fm.png"),
const Country(name: "Moldova", countryCode: "MD", dialCode: "+373", emoji: "🇲🇩", flagUri: "assets/svg/md.png"),
const Country(name: "Monaco", countryCode: "MC", dialCode: "+377", emoji: "🇲🇨", flagUri: "assets/svg/mc.png"),
const Country(name: "Mongolia", countryCode: "MN", dialCode: "+976", emoji: "🇲🇳", flagUri: "assets/svg/mn.png"),
const Country(name: "Montenegro", countryCode: "ME", dialCode: "+382", emoji: "🇲🇪", flagUri: "assets/svg/me.png"),
const Country(name: "Montserrat", countryCode: "MS", dialCode: "+1664", emoji: "🇲🇸", flagUri: "assets/svg/ms.png"),
const Country(name: "Morocco", countryCode: "MA", dialCode: "+212", emoji: "🇲🇦", flagUri: "assets/svg/ma.png"),
const Country(name: "Mozambique", countryCode: "MZ", dialCode: "+258", emoji: "🇲🇿", flagUri: "assets/svg/mz.png"),
const Country(name: "Myanmar", countryCode: "MM", dialCode: "+95", emoji: "🇲🇲", flagUri: "assets/svg/mm.png"),
const Country(name: "Namibia", countryCode: "NA", dialCode: "+264", emoji: "🇳🇦", flagUri: "assets/svg/na.png"),
const Country(name: "Nauru", countryCode: "NR", dialCode: "+674", emoji: "🇳🇷", flagUri: "assets/svg/nr.png"),
const Country(name: "Nepal", countryCode: "NP", dialCode: "+977", emoji: "🇳🇵", flagUri: "assets/svg/np.png"),
const Country(name: "Netherlands", countryCode: "NL", dialCode: "+31", emoji: "🇳🇱", flagUri: "assets/svg/nl.png"),
const Country(name: "Netherlands Antilles", countryCode: "AN", dialCode: "+599", emoji: "🇦🇳", flagUri: "assets/svg/an.png"),
const Country(name: "New Caledonia", countryCode: "NC", dialCode: "+687", emoji: "🇳🇨", flagUri: "assets/svg/nc.png"),
const Country(name: "New Zealand", countryCode: "NZ", dialCode: "+64", emoji: "🇳🇿", flagUri: "assets/svg/nz.png"),
const Country(name: "Nicaragua", countryCode: "NI", dialCode: "+505", emoji: "🇳🇮", flagUri: "assets/svg/ni.png"),
const Country(name: "Niger", countryCode: "NE", dialCode: "+227", emoji: "🇳🇪", flagUri: "assets/svg/ne.png"),
const Country(name: "Nigeria", countryCode: "NG", dialCode: "+234", emoji: "🇳🇬", flagUri: "assets/svg/ng.png"),
const Country(name: "Niue", countryCode: "NU", dialCode: "+683", emoji: "🇳🇺", flagUri: "assets/svg/nu.png"),
const Country(name: "Norfolk Island", countryCode: "NF", dialCode: "+672", emoji: "🇳🇫", flagUri: "assets/svg/nf.png"),
const Country(name: "Northern Mariana Islands", countryCode: "MP", dialCode: "+1670", emoji: "🇲🇵", flagUri: "assets/svg/mp.png"),
const Country(name: "Norway", countryCode: "NO", dialCode: "+47", emoji: "🇳🇴", flagUri: "assets/svg/no.png"),
const Country(name: "Oman", countryCode: "OM", dialCode: "+968", emoji: "🇴🇲", flagUri: "assets/svg/om.png"),
const Country(name: "Pakistan", countryCode: "PK", dialCode: "+92", emoji: "🇵🇰", flagUri: "assets/svg/pk.png"),
const Country(name: "Palau", countryCode: "PW", dialCode: "+680", emoji: "🇵🇼", flagUri: "assets/svg/pw.png"),
const Country(name: "Palestinian Territory, Occupied", countryCode: "PS", dialCode: "+970", emoji: "🇵🇸", flagUri: "assets/svg/ps.png"),
const Country(name: "Panama", countryCode: "PA", dialCode: "+507", emoji: "🇵🇦", flagUri: "assets/svg/pa.png"),
const Country(name: "Papua New Guinea", countryCode: "PG", dialCode: "+675", emoji: "🇵🇬", flagUri: "assets/svg/pg.png"),
const Country(name: "Paraguay", countryCode: "PY", dialCode: "+595", emoji: "🇵🇾", flagUri: "assets/svg/py.png"),
const Country(name: "Peru", countryCode: "PE", dialCode: "+51", emoji: "🇵🇪", flagUri: "assets/svg/pe.png"),
const Country(name: "Philippines", countryCode: "PH", dialCode: "+63", emoji: "🇵🇭", flagUri: "assets/svg/ph.png"),
const Country(name: "Pitcairn", countryCode: "PN", dialCode: "+872", emoji: "🇵🇳", flagUri: "assets/svg/pn.png"),
const Country(name: "Poland", countryCode: "PL", dialCode: "+48", emoji: "🇵🇱", flagUri: "assets/svg/pl.png"),
const Country(name: "Portugal", countryCode: "PT", dialCode: "+351", emoji: "🇵🇹", flagUri: "assets/svg/pt.png"),
const Country(name: "Puerto Rico", countryCode: "PR", dialCode: "+1939", emoji: "🇵🇷", flagUri: "assets/svg/pr.png"),
const Country(name: "Qatar", countryCode: "QA", dialCode: "+974", emoji: "🇶🇦", flagUri: "assets/svg/qa.png"),
const Country(name: "Romania", countryCode: "RO", dialCode: "+40", emoji: "🇷🇴", flagUri: "assets/svg/ro.png"),
const Country(name: "Russia", countryCode: "RU", dialCode: "+7", emoji: "🇷🇺", flagUri: "assets/svg/ru.png"),
const Country(name: "Rwanda", countryCode: "RW", dialCode: "+250", emoji: "🇷🇼", flagUri: "assets/svg/rw.png"),
const Country(name: "Reunion", countryCode: "RE", dialCode: "+262", emoji: "🇷🇪", flagUri: "assets/svg/re.png"),
const Country(name: "Saint Barthelemy", countryCode: "BL", dialCode: "+590", emoji: "🇧🇱", flagUri: "assets/svg/bl.png"),
const Country(name: "Saint Helena, Ascension and Tristan Da Cunha", countryCode: "SH", dialCode: "+290", emoji: "🇸🇭", flagUri: "assets/svg/sh.png"),
const Country(name: "Saint Kitts and Nevis", countryCode: "KN", dialCode: "+1869", emoji: "🇰🇳", flagUri: "assets/svg/kn.png"),
const Country(name: "Saint Lucia", countryCode: "LC", dialCode: "+1758", emoji: "🇱🇨", flagUri: "assets/svg/lc.png"),
const Country(name: "Saint Martin", countryCode: "MF", dialCode: "+590", emoji: "🇲🇫", flagUri: "assets/svg/mf.png"),
const Country(name: "Saint Pierre and Miquelon", countryCode: "PM", dialCode: "+508", emoji: "🇵🇲", flagUri: "assets/svg/pm.png"),
const Country(name: "Saint Vincent and the Grenadines", countryCode: "VC", dialCode: "+1784", emoji: "🇻🇨", flagUri: "assets/svg/vc.png"),
const Country(name: "Samoa", countryCode: "WS", dialCode: "+685", emoji: "🇼🇸", flagUri: "assets/svg/ws.png"),
const Country(name: "San Marino", countryCode: "SM", dialCode: "+378", emoji: "🇸🇲", flagUri: "assets/svg/sm.png"),
const Country(name: "Sao Tome and Principe", countryCode: "ST", dialCode: "+239", emoji: "🇸🇹", flagUri: "assets/svg/st.png"),
const Country(name: "Saudi Arabia", countryCode: "SA", dialCode: "+966", emoji: "🇸🇦", flagUri: "assets/svg/sa.png"),
const Country(name: "Senegal", countryCode: "SN", dialCode: "+221", emoji: "🇸🇳", flagUri: "assets/svg/sn.png"),
const Country(name: "Serbia", countryCode: "RS", dialCode: "+381", emoji: "🇷🇸", flagUri: "assets/svg/rs.png"),
const Country(name: "Seychelles", countryCode: "SC", dialCode: "+248", emoji: "🇸🇨", flagUri: "assets/svg/sc.png"),
const Country(name: "Sierra Leone", countryCode: "SL", dialCode: "+232", emoji: "🇸🇱", flagUri: "assets/svg/sl.png"),
const Country(name: "Singapore", countryCode: "SG", dialCode: "+65", emoji: "🇸🇬", flagUri: "assets/svg/sg.png"),
const Country(name: "Slovakia", countryCode: "SK", dialCode: "+421", emoji: "🇸🇰", flagUri: "assets/svg/sk.png"),
const Country(name: "Slovenia", countryCode: "SI", dialCode: "+386", emoji: "🇸🇮", flagUri: "assets/svg/si.png"),
const Country(name: "Solomon Islands", countryCode: "SB", dialCode: "+677", emoji: "🇸🇧", flagUri: "assets/svg/sb.png"),
const Country(name: "Somalia", countryCode: "SO", dialCode: "+252", emoji: "🇸🇴", flagUri: "assets/svg/so.png"),
const Country(name: "South Africa", countryCode: "ZA", dialCode: "+27", emoji: "🇿🇦", flagUri: "assets/svg/za.png"),
const Country(name: "South Sudan", countryCode: "SS", dialCode: "+211", emoji: "🇸🇸", flagUri: "assets/svg/ss.png"),
const Country(name: "South Georgia and the South Sandwich Islands", countryCode: "GS", dialCode: "+500", emoji: "🇬🇸", flagUri: "assets/svg/gs.png"),
const Country(name: "Spain", countryCode: "ES", dialCode: "+34", emoji: "🇪🇸", flagUri: "assets/svg/es.png"),
const Country(name: "Sri Lanka", countryCode: "LK", dialCode: "+94", emoji: "🇱🇰", flagUri: "assets/svg/lk.png"),
const Country(name: "Sudan", countryCode: "SD", dialCode: "+249", emoji: "🇸🇩", flagUri: "assets/svg/sd.png"),
const Country(name: "Suriname", countryCode: "SR", dialCode: "+597", emoji: "🇸🇷", flagUri: "assets/svg/sr.png"),
const Country(name: "Svalbard and Jan Mayen", countryCode: "SJ", dialCode: "+47", emoji: "🇸🇯", flagUri: "assets/svg/sj.png"),
const Country(name: "Swaziland", countryCode: "SZ", dialCode: "+268", emoji: "🇸🇿", flagUri: "assets/svg/sz.png"),
const Country(name: "Sweden", countryCode: "SE", dialCode: "+46", emoji: "🇸🇪", flagUri: "assets/svg/se.png"),
const Country(name: "Switzerland", countryCode: "CH", dialCode: "+41", emoji: "🇨🇭", flagUri: "assets/svg/ch.png"),
const Country(name: "Syrian Arab Republic", countryCode: "SY", dialCode: "+963", emoji: "🇸🇾", flagUri: "assets/svg/sy.png"),
const Country(name: "Taiwan", countryCode: "TW", dialCode: "+886", emoji: "🇹🇼", flagUri: "assets/svg/tw.png"),
const Country(name: "Tajikistan", countryCode: "TJ", dialCode: "+992", emoji: "🇹🇯", flagUri: "assets/svg/tj.png"),
const Country(name: "Tanzania, United Republic of Tanzania", countryCode: "TZ", dialCode: "+255", emoji: "🇹🇿", flagUri: "assets/svg/tz.png"),
const Country(name: "Thailand", countryCode: "TH", dialCode: "+66", emoji: "🇹🇭", flagUri: "assets/svg/th.png"),
const Country(name: "Timor-Leste", countryCode: "TL", dialCode: "+670", emoji: "🇹🇱", flagUri: "assets/svg/tl.png"),
const Country(name: "Togo", countryCode: "TG", dialCode: "+228", emoji: "🇹🇬", flagUri: "assets/svg/tg.png"),
const Country(name: "Tokelau", countryCode: "TK", dialCode: "+690", emoji: "🇹🇰", flagUri: "assets/svg/tk.png"),
const Country(name: "Tonga", countryCode: "TO", dialCode: "+676", emoji: "🇹🇴", flagUri: "assets/svg/to.png"),
const Country(name: "Trinidad and Tobago", countryCode: "TT", dialCode: "+1868", emoji: "🇹🇹", flagUri: "assets/svg/tt.png"),
const Country(name: "Tunisia", countryCode: "TN", dialCode: "+216", emoji: "🇹🇳", flagUri: "assets/svg/tn.png"),
const Country(name: "Turkey", countryCode: "TR", dialCode: "+90", emoji: "🇹🇷", flagUri: "assets/svg/tr.png"),
const Country(name: "Turkmenistan", countryCode: "TM", dialCode: "+993", emoji: "🇹🇲", flagUri: "assets/svg/tm.png"),
const Country(name: "Turks and Caicos Islands", countryCode: "TC", dialCode: "+1649", emoji: "🇹🇨", flagUri: "assets/svg/tc.png"),
const Country(name: "Tuvalu", countryCode: "TV", dialCode: "+688", emoji: "🇹🇻", flagUri: "assets/svg/tv.png"),
const Country(name: "Uganda", countryCode: "UG", dialCode: "+256", emoji: "🇺🇬", flagUri: "assets/svg/ug.png"),
const Country(name: "Ukraine", countryCode: "UA", dialCode: "+380", emoji: "🇺🇦", flagUri: "assets/svg/ua.png"),
const Country(name: "United Arab Emirates", countryCode: "AE", dialCode: "+971", emoji: "🇦🇪", flagUri: "assets/svg/ae.png"),
const Country(name: "United Kingdom", countryCode: "GB", dialCode: "+44", emoji: "🇬🇧", flagUri: "assets/svg/gb.png"),
const Country(name: "United States", countryCode: "US", dialCode: "+1", emoji: "🇺🇸", flagUri: "assets/svg/us.png"),
const Country(name: "Uruguay", countryCode: "UY", dialCode: "+598", emoji: "🇺🇾", flagUri: "assets/svg/uy.png"),
const Country(name: "Uzbekistan", countryCode: "UZ", dialCode: "+998", emoji: "🇺🇿", flagUri: "assets/svg/uz.png"),
const Country(name: "Vanuatu", countryCode: "VU", dialCode: "+678", emoji: "🇻🇺", flagUri: "assets/svg/vu.png"),
const Country(name: "Venezuela, Bolivarian Republic of Venezuela", countryCode: "VE", dialCode: "+58", emoji: "🇻🇪", flagUri: "assets/svg/ve.png"),
const Country(name: "Vietnam", countryCode: "VN", dialCode: "+84", emoji: "🇻🇳", flagUri: "assets/svg/vn.png"),
const Country(name: "Virgin Islands, British", countryCode: "VG", dialCode: "+1284", emoji: "🇻🇬", flagUri: "assets/svg/vg.png"),
const Country(name: "Virgin Islands, U.S.", countryCode: "VI", dialCode: "+1340", emoji: "🇻🇮", flagUri: "assets/svg/vi.png"),
const Country(name: "Wallis and Futuna", countryCode: "WF", dialCode: "+681", emoji: "🇼🇫", flagUri: "assets/svg/wf.png"),
const Country(name: "Yemen", countryCode: "YE", dialCode: "+967", emoji: "🇾🇪", flagUri: "assets/svg/ye.png"),
const Country(name: "Zambia", countryCode: "ZM", dialCode: "+260", emoji: "🇿🇲", flagUri: "assets/svg/zm.png"),
const Country(name: "Zimbabwe", countryCode: "ZW", dialCode: "+263", emoji: "🇿🇼", flagUri: "assets/svg/zw.png"),

];
  